### ISSUE TITLE
Implement 'Show more / Show less' button to longer texts on About page

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#1091]
Steps to reproduce:
- Go to /about page.
- Observe Management board section - the descriptions are too long:

![image](https://user-images.githubusercontent.com/14351733/200611594-8a4f0bad-6b16-4c70-974e-d39818c637e5.png)

Expectation: Implement 'Show more / Show less' buttons under the longer descriptions.

**Comment by AndreyGoranov** [comment]
I am starting to work on it  =]

**Comment by kachar** [comment]
@AndreyGoranov @ivoka9 We've got an interesting situation regarding this task.

We've ended up having two separate PRs with different implementations of the same reported problem.
Thanks for your devotion and energy spent on it. :zap: 

Now we've got to keep only one of the following two versions which solves the problem.

- https://github.com/podkrepi-bg/frontend/pull/1148 :a:
- https://github.com/podkrepi-bg/frontend/pull/1139 :b:

I invite you to collaborate and help the team decide how to proceed. I see two authentic ways to solve the task, now we've got to decide if we keep :a:, :b: or create a 3rd way combined way :cactus: of handling it.

In order to avoid this double work again I urge everyone to check if the ticket has an assignee and pick another available one instead.

**Comment by ivoka9** [comment]
First of all I want to start with an apology for not assigning it to myself, but for  the life of me I could not figure out how to as I don't see the button, (based on my google search I have to first contribute in order to be able to assign myself ?)

Second I do find it a bit hard to criticize my own method as I am biased, but here is my takeaway 

My method is more simple, and maybe under some conditions will break as I use hardcoded values 50/200 etc... 
but the upside is that if needed it would be easy/easier to correct or refactor,
also it re uses the already implemented button, giving the whole application a more consistent UI/UX as the user does not experience "new things"

His method seems more advanced as it gives a certain number of rows that would display, also it takes the user screen view into consideration, making some "complex equations" to consider what should show.
I don't like the  the "show" === "Покажи повече" , and the fact that the button is new (or I personally have not seen it in the app)
also not a huge supporter of the Tuples

I am  more then happy to collaborate on this or any other issue but assuming that he is Bulgaria I am currently in the US there is 7 hours difference it it would make it a nightmare.

If possible close it with the best possible solution or take my feedback and give me/him the ability to finish what we have started, and lets move to the next complicated ticket :)

**Comment by ani-kalpachka** [comment]
I personally prefer solution B because the implementation seems simpler and it would be easier to maintain.
Please share more opinions.

**Comment by AndreyGoranov** [comment]
I guess my approach might be an overkill for the app needs. My first approach was simply passing a string limit and using the substring method. But I didn't like the UX so I tried making it more smooth. About the "Покажи повече" it can always be changed to a button. If we plan using more expandable texts around the app this could serve well but I am still getting to know the app so I don't really know whats best at that point.

**Comment by AndreyGoranov** [comment]
@ani-kalpachka  I am ok with it.
