### ISSUE TITLE
[Bug] Payment import: User feedback message on donation import operations

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#1137]
Currently we have two messages for feedback after payments import - "ok" and "error". This information is not enough should be changed:

A bank account movement can be:

1. **Already imported** (we compare "DocumentReference" tag with ext_payment_intent_id  filed in the DB, hopefully also cheking dates) 
Message: 
Updated payments: 
"OppositeSideName" "ProcessTimestamp" "AmountInMovementCCY" "MovementCCY" 
... (each updated record is listed)

Please note: If a bank donation is updated we should have audit trail history for all changes.   

2.  **Skipped** - These are all the expenses, payments from Stripe and other payment providers as well aspayments with no reason quoted 
Message: 
Skipped payments:
"OppositeSideName" "ProcessTimestamp" "AmountInMovementCCY" "MovementCCY"    
... (each skipped record is listed)

3.  **Successfully imported** - campaign code is found and there are no other errors 
Message:
Successfully imported X donations for the amount of XX BGN for the following campaings 
Campaign XXX - YYYY  BGN 
...

5. **Unsuccessfully imported** - No valid campaign code is found <NarrativeI02> or other problem 
Message: 
"OppositeSideName" "ProcessTimestamp" "AmountInMovementCCY" "MovementCCY" import fail reason 

If there are no skipped / updated / unsuccessfully / successfully  imported donations, these message sections should not be visible 

Having said that - currently if the import procedure does not allow partial import of data - if the first error is found the whole operatio in aborted. This will be the subject of a different issue.

**Comment by Nnachevvv** [comment]
I would like to take this bug :)

**Comment by Nnachevvv** [comment]
From the task it seems we should use Alert/Snackbar mechanism to alert admin user. 
To be honest I'm not 100% percent sure that this would be the best approach to notify the admin user, because I'm not aware how many donation one file can have. If the donations are too many, this implementation may have a trouble displaying all of them  . 
Results from notifying the user with Alert:
<img width="1740" alt="Screenshot 2022-12-21 at 12 38 09" src="https://user-images.githubusercontent.com/44066540/208886064-2419ce36-3249-46eb-ae78-fd31018d3a09.png">
So would you confirm if this the required solution? I'm also open to any suggestions :)

**Comment by kachar** [comment]
@Nnachevvv We can have a dedicated page for the import and show the info messages on full screen.

**Comment by igoychev** [comment]
Just FYI: 
We are moving ahead with integrating automated bank imports via bank integration webhook, however until that is ready we still need a minimum import stats here. 

So @Nnachevvv could you show the import stats in a readonly text field so that it can contain more info. If not, then the stats could be simply the following: 
 - Already imported rows: count
 - Skipped: count
 - Errors (count) with row ids: 2, 7, 8, 9 
All the rest are successful.
