### ISSUE TITLE
[Bug] XML Bank payments import - incorrect time 

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#1204]
The timestamp of the bank import XML file is in Bank account local time zone (UTC +2). 
I guess the time stamp in database is in UTC. 
Therefore there is a 2 hours time difference between the time 

We should consider fixing this by:
1. Define bank account time zone 
2.  Adjust the timestamp for xml tags PaymentDateTime and ProcessTimestamp during the import with the time zone difference from UTC

**Comment by igoychev** [comment]
To make this a low-hanging fruit, the problem is in the backend repo on this line:

https://github.com/podkrepi-bg/api/blob/615124da8d32b74112de4213479be4cd0dd98920/apps/api/src/bank-transactions-file/helpers/parser.ts#L26

**Comment by dimitur2204** [comment]
> I guess the time stamp in database is in UTC.
Therefore there is a 2 hours time difference between the time

I am struggling to understand the issue. Where exactly is the "2 hours time difference between the time"?
How the JS `Date` object works is it under the hood uses UTC and it's `toString` method returns local time.

**Comment by igoychev** [comment]
I did some more checks to find the root cause of this issue:
 The import file for Karavelovo flooded villages campaign contains the date as this:
 `<PaymentDateTime>2022-11-18T09:03:31</PaymentDateTime>`
and on the UI it is displayed as 
`18 Nov 2022 11:03:31`

So @Juicebgs, which one is the expected behavior?
- [current] The XML contains UTC, and the web site should adjust +2h as per the Sofia, Bulgaria Locale
- The XML contains GMT+2 and the web site should display same time without change

**Comment by Juicebgs** [comment]
> * The XML contains GMT+2 and the web site should display same time without change
This is the right one. Example:
A donation imported from the bank:
![image](https://user-images.githubusercontent.com/74968982/205484957-4f7ac098-30a0-41df-8991-f51a43b63f86.png)
XML:
    <<PaymentDateTime>2022-11-24T10:54:10</PaymentDateTime>>
Bank:
![image](https://user-images.githubusercontent.com/74968982/205485063-9bcc7de8-2740-4c56-a52c-c7130098d69d.png)

**Comment by Nnachevvv** [comment]
Would you assign me. I would like to work on this bug.

**Comment by Nnachevvv** [comment]
I have a few questions about the bank transactions format:
1. Is there a way to test this? I couldn't find anywhere a XML file, which I can upload in order to test the workflow?
2. What is the format of the XML file for the bank transactions? 
3. Do we always expect to receive date in the following format from the YYYY-MM-DDTHH:MM:SS xml file? If this this is the case, I see as solution to append the desired timezone(+0200) every time we process the PaymentDateTime variable.

**Comment by igoychev** [comment]
> I have a few questions about the bank transactions format:
> 
>     1. Is there a way to test this? I couldn't find anywhere a XML file, which I can upload in order to test the workflow?
> 
>     2. What is the format of the XML file for the bank transactions?
> 
>     3. Do we always expect to receive date in the following format from the YYYY-MM-DDTHH:MM:SS xml file? If this this is the case, I see as solution to append the desired timezone(+0200) every time we process the PaymentDateTime variable.

Yes, see attached a test import file you can use - it contains fake data with the expected xml format. 
The date format is always the same as in the file and yes, the fix might be just adding the timezone before the date is parsed.
[22_11_18_TestImport.xml.txt](https://github.com/podkrepi-bg/frontend/files/10164078/22_11_18_TestImport.xml.txt)
