### ISSUE TITLE
[Bug] Registered user - no initials of the user in his/her profile 

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#1218]
No initials for the registered user when he/ she is in the profile

1. Go to podkrepi.bg 
2. Click on Вход/ Регистрация
3. The profile is opened but the user is not sure about this cause he/she doesn't see his initials. For example for Polina Mihaylova - PM 

In the Desktop version it is not reproducible. Everything is OK there. Just via Mobile device![Screenshot_20221130-124141_Chrome.jpg](https://user-images.githubusercontent.com/77857494/204775914-b8a94898-5aaa-43e0-a98e-26e5fafd7241.jpg)

On contrary the Desktop version with the same user has initials (refer to the attached picture)

![20221130_124718.jpg](https://user-images.githubusercontent.com/77857494/204776576-00e2cd09-e525-4e0e-8977-7c6fe0f1b1cf.jpg)

**Comment by ani-kalpachka** [comment]
The initials for logged user on desktop are displayed in the navigation menu as an icon so the user can access his/her profile. For this goal on mobile we have the 'Profile' button in the mobile navigation menu. I suggest we keep the button for mobile rather than the initials icon. What do you think?

**Comment by ani-kalpachka** [comment]
Closing the ticket as discussed with @Polina1985.
