### ISSUE TITLE
[Fonts] Change Campaign page body/paragraph to use commissioner as per design system 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1354]
### Describe the Bug

https://podkrepi.bg/campaigns/da-sbudnem-mechtata-na-valeriya-da-vleze-v-top-5-na-evropa-v-tenisa

### To Reproduce

all campaigns

### Expected Behavior

Commissioner

**Comment by ani-kalpachka** [comment]
If we need to switch from Montserrat to Lato font do you think it would be better to apply it on each page and not only for Campaign's details page? We are using Montserrat font everywhere on the site. I think we should have one main font for each page in order to preserve the consistency. Please advice.

**Comment by swolf86** [comment]
I think the font used for the body is Helvetica at the moment on the campaign page - please confrirm - it doesn't look for Montserrat.  We planned Montserrat for headings and lato for body- but if this is lato we might need to change it
![image](https://user-images.githubusercontent.com/75036745/219980772-0aee716d-8dce-46fe-a296-c1d3b3d2ecfc.png)

do you know what is this body font ?
![image](https://user-images.githubusercontent.com/75036745/219980984-409e4a95-77b7-4c07-a632-403ce5b6821b.png)

**Comment by swolf86** [comment]
finally the paragraph font should be commissioner
