### ISSUE TITLE
[Bug] Google Login does not work

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1389]
### Describe the Bug

Trying to log with google login refreshes the page instead of redirecting and handling the login.

### To Reproduce

1. Go to login page on https://podkrepi.bg
2. Click Sign in with Google
3. Watch it refresh the page

### Expected Behavior

People should be able to login with Google

### Which browser are you using? (if relevant)

Chrome 111.0.5563.64

**Comment by sashko9807** [comment]
Unable to completely reproduce in local environment. The closest I could get to replicate the issue is by removing the google  ID from env.  Someone with proper access to configurations and server logs should take a look at this.

The good news is that the Google login does work, if you are persistent and patient enough, to click on the button until it does.

**Comment by sashko9807** [comment]
Unable to reproduce in either prod or stage environments anymore. @dimitur2204 can you check as well if this issue is still valid or not

**Comment by dimitur2204** [comment]
We talked with @igoychev that it got fixed together with the Stripe problems, but forgot to close the issue!
