### ISSUE TITLE
[Campaigns] Group Filter by Categories

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1638]
### Describe the feature you'd like to request

Please remove/hide inactive categories. 

![image](https://github.com/podkrepi-bg/frontend/assets/75036745/550bbe1d-ad95-4c6b-b72b-be555b77bee6)

### Describe the solution you'd like

Please indicate that all campaigns is selected

**Comment by dimitur2204** [comment]
Is this what you mean @swolf86 
<img width="1260" alt="image" src="https://github.com/podkrepi-bg/frontend/assets/61479393/8032c894-9ae3-4657-b84a-f28ffa5b9473">

**Comment by swolf86** [comment]
@dimitur2204 yes

**Comment by igoychev** [comment]
Some feedback, now that I see the implementation:
With less categories it feels as if the list is incomplete, because there is nothing left to indicates there might be other possible categories. 

I am not aware of the initial reason for the change, but please consider alternatives like:
- If the reason was to save space, then may be icons can be made smaller.
- If the reason was for current categories to not feel as disabled (being grey) - let's make them in active(clickable) color, the underlining/bolding could indicate well the selected one

@swolf86 @dimitur2204 
Of course, if you still want to go with not showing all categories, then let's please at least center them.

**Comment by swolf86** [comment]
Inactive categories should not be presented to the user. With many categories we create false impression we have many cayegories. To facilitate choise let show just active categories. We can align them in the middle. Let me see how it can work. 
 I think we have social campaigns too

Initiation of the task From Luctat UX audits and @MartinaMitz

**Comment by ani-kalpachka** [comment]
I am closing the issue and the pull request based on the last discussions and the vote of the team.
If a different decision is made in the future, we can use the code provided here: https://github.com/podkrepi-bg/frontend/pull/1641
