### ISSUE TITLE
[Feature] Post production deployments to Discord #website channel

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#220]
In order to inform everyone in Discord server that we've deployed to production we need a hook to inform the #уебсайт channel when deployment workflow completes

Sample workflow: https://github.com/daritelska-platforma/frontend/actions/runs/904181961

**Comment by skilldeliver** [comment]
Hello, @kachar , can you provide a little bit more information how we can achieve this? I think we should write some kind of a custom webhook, I've tested twice the [default way](https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22#step-2---set-up-the-webhook-on-github) of achieving integration between Discord and GitHub and unfortunately Discord supports limited types of events (PRs, issues, stars added).

**Comment by kachar** [comment]
@skilldeliver I think we can use it inside one of our deployment actions with a dedicated github action

- https://github.com/marketplace/actions/actions-for-discord
- https://github.com/Ilshidur/action-discord
- https://github.com/marketplace/actions/actions-status-discord

**Comment by skilldeliver** [comment]
@kachar nice, I've checked them, [this one](https://github.com/marketplace/actions/actions-status-discord
) I think will be better to use because it uses only one secret (DISCORD_WEBHOOK URL) compared with the first one where you need both ID of the webhook and token of the channel. Also it provides more information by default into the embed.

![image](https://user-images.githubusercontent.com/37806520/122769324-252fd900-d2ad-11eb-8ead-a2a76d98d92c.png)

I can open a PR for the workflow and send you the URL of the webhook privately(Discord DM) to be added as a secret. What do you think?

**Comment by kachar** [comment]
@skilldeliver Sounds great, you might use the var `APP_DISCORD_WEBHOOK` as we already have similar discord vars (for a testing discord login app)

**Comment by igoychev** [comment]
closed as per #280
