### ISSUE TITLE
[Bug] [backend] Sending XSS payload via API URL route path

### ISSUE THREAD

**Issue by spazbg** [podkrepi-bg/frontend#232]
An attacker can send a malicious XSS payload witch will reflect in the response. 
If the attacker finds another misconfiguration, he can try to make the this XSS stored or to chain it with an open redirect or another attack vector.

![image](https://user-images.githubusercontent.com/22222777/120891934-0cb89100-c614-11eb-87f7-aff95f225d26.png)

XSS PoC
![image](https://user-images.githubusercontent.com/22222777/120891944-1e9a3400-c614-11eb-8d7e-30ac525462a2.png)

PS: Possible reason - Try-catch with Console.WriteLine(error)

---

Steps to reproduce:

```shell
$ curl 'https://podkrepi.bg/api/auth/providers;<script>alert(1)</script>'
Error: HTTP GET is not supported for /api/auth/providers;<script>alert(1)</script>
```

**Comment by kachar** [comment]
@spazbg Thanks for the report, great finding :rocket: :closed_lock_with_key:  

It seems the problem is caused by Next.js dynamic routes accepting the value and then a dependency project printing the error message containing the url without proper url encoding.

I've contacted the maintainer of the repo in private to ensure that the XSS is not disclosed before it has a fix.

**Comment by spazbg** [comment]
Good job 👍
I am waiting for updates :)

**Comment by kachar** [comment]
We've got no updates so far from the maintainers, anyhow few months back we've replaced the next-auth implementation with keycloak-js, so this issue is no longer active

**Comment by spazbg** [comment]
Thank you for the update :)
