### ISSUE TITLE
[Bug] Minor - Home page/ UI-UX - visual discrepancy 

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#544]
Describe the bug
Home page - UX/UI discrepancy-   Headers - "Мисия", "Визия" и "Цели" 

**To Reproduce**

1. Go to podkrepi.bg
2. Scroll down to Headers - "Мисия", "Визия" и "Цели"
3. Menu "Цели' - there are dashes in the text, while the text in other "Мисия" and "Визия" do not have dashes

**Expected behavior**
Equal UI text 

**Screenshots**
![dashes](https://user-images.githubusercontent.com/77857494/155704392-aa180055-fcd3-4184-a22c-64981238b1bc.jpg)

**Desktop (please complete the following information):**

- OS: Windows
- Browser - Chrome
- Version

**Comment by ani-kalpachka** [comment]
Hello, @Polina1985!

The design of Homepage is going to be fully changed soon and this issue is not going to be present. Here is the new design: https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=3904%3A13406

I suggest we don't spend time on it since this whole section will look different after implementing the new changes. Could you confirm this?
