### ISSUE TITLE
[Bug] [Major] Edit your profile function is not working

### ISSUE THREAD

**Issue by petarrr1** [podkrepi-bg/frontend#793]
**Describe the bug**
Cannot use the "редактирай" function on My Profile page

**To Reproduce**

1. Go to 'Homepage'
2. Login 
3. Go to My Profile
4. Click on "редактирай"
5. See the error 

**Expected behavior**
to be allowed to edit your profile information 

**Actual behavior**
"Редактирай" button is refreshing the page

**Screenshots**
![Screenshot 2022-05-26 at 15 12 42](https://user-images.githubusercontent.com/105493182/170486097-beec4fb8-e9aa-4ff2-8018-86d7dc17e50b.png)

Desktop: 
OS: macOS Catalina 10.15.7 
Browser: safari
Version [15.4]

**Comment by Bunny303** [comment]
Edit of profile is working properly, see attached pictures. In the picture above user information is not loaded that's why filed "Име" is empty. Probbaly on registration user is not created properly or on login is not loaded properly. If it's happening every time then try to register new user.
![image](https://user-images.githubusercontent.com/3616912/172050071-e253c62e-58a1-476a-a4c2-1fe0754db897.png)
![image](https://user-images.githubusercontent.com/3616912/172050082-638a2716-6028-4743-a9c7-d1bdb41c72f6.png)

**Comment by petarrr1** [comment]
Try to edit your password
