### ISSUE TITLE
[Bug] [Major] "Предложи нова кампания" feature is not working 

### ISSUE THREAD

**Issue by petarrr1** [podkrepi-bg/frontend#795]
**Describe the bug**
after filling all the information about the campaign the "Изпрати" button is not woking

**To Reproduce**

1. Go to 'Homepage'
2. Click on 'Дарителство'
3. Click on  'Предложи кампания' https://dev.podkrepi.bg/campaigns/create
4. Fill all the information about the campaign 
5. Tick all 2 checkboxes 
6. Click on "Изпрати" button 

**Expected behavior**
The campaign is sent successfully

**Actual behavior**
After clicking on the "Изпрати" button nothing happens

Desktop
OS: macOS Catalina 10.15.7 
Browser: safari
Version [15.4]

**Comment by valkirilov** [comment]
Is this bug still relevant? I managed to reproduce it, but I don't find any link which can lead me to this page as it is described in the retro steps above. I had to manually type the URL in trhe browser in order to reach the page and try to create a new campaign. 

So I wonder whether this feature is still something we need or it was temporary drooped out of the current release?

**Comment by ani-kalpachka** [comment]
The ticket seems to be outdated.
Currently we do not support the page.
I will close the ticket. If we enable the page again in the future and the issue is still valid, please feel free to reopen it.
