### ISSUE TITLE
[Bug] Google Authentication issues

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#981]
**Describe the bug**
We have received several emails (feedback@podkrepi.bg) from people unable to login with their google accounts. If the problem is resolved, please mark as invalid.

**Comment by imilchev** [comment]
I am curious if we know the emails they had issues logging in with. I just tested and I am able to authenticate with google just fine. However, if you created the account manually with your google email (just manually fill in your data and provide a google mail as an email) and later try to login through the google integration that does not work. This is also not intended by the way. If you create the account manually, it has a password so you cannot log in via the integration. The opposite applies to too - if you created your account via the integration, you cannot login with a password.

Please provide some of the mails that mentioned this issue. I believe we can check whether the existing account is linked to a google account or if it's manual. Then we can confirm what the root cause is. I am almost certain that it is the case that I described above. If that's true then we actually need to provide an error back, because when logging in fails, there is no error message on the screen stating that your account is using password authentication.

P.S.: We can also check this on discord, so you don't have to publish the emails of people here.

**Comment by Juicebgs** [comment]
@imilchev I will send information via discord because emails are considered sensitive data under GDPR.

**Comment by igoychev** [comment]
we need to improve the error message on these failed attempts, so that both users and us now more what causes them

**Comment by rkgeorgiev** [comment]
I believe I found what causes this issue.
Its caused by trying to donate by opening a link via Facebook native app (it opens podkrepi.bg via FB browser. If you try to Login with google after that while in FB browser the useragent is forbidden.

Steps:
1. Open a Donation link via Facebook native app
2. Click to donate
3. On the Login step choose login with google
4. Insert your email & password

Actual: You get an error that the user agent is forbidden and you cannot proceed with the donation 
![315090592_832667154597288_5365002690334922688_n (1)](https://user-images.githubusercontent.com/18218058/201870500-7bc4793d-ab15-47f8-aa77-9765291052b0.jpg)
